CREATE TABLE "events" (
	"id" varchar(36) PRIMARY KEY NOT NULL,
	"title" text NOT NULL,
	"description" text NOT NULL,
	"date" text NOT NULL,
	"time" text NOT NULL,
	"location" text NOT NULL,
	"capacity" integer NOT NULL,
	"registered_count" integer DEFAULT 0 NOT NULL,
	"image_url" text,
	"is_active" boolean DEFAULT true NOT NULL,
	"requires_registration" boolean DEFAULT true NOT NULL
);
--> statement-breakpoint
CREATE TABLE "participant_registrations" (
	"id" varchar(36) PRIMARY KEY NOT NULL,
	"first_name" text NOT NULL,
	"middle_initial" text,
	"last_name" text NOT NULL,
	"street" text NOT NULL,
	"city" text NOT NULL,
	"state" text NOT NULL,
	"postal_code" text NOT NULL,
	"country" text NOT NULL,
	"email" text NOT NULL,
	"mobile_phone" text,
	"work_phone" text,
	"home_phone" text,
	"preferred_phone" text NOT NULL,
	"birth_year" integer NOT NULL,
	"gender" text NOT NULL,
	"ethnicity" text NOT NULL,
	"military_status" text NOT NULL,
	"is_disabled_veteran" boolean NOT NULL,
	"uses_va" boolean NOT NULL,
	"branch_of_service" text NOT NULL,
	"deployments" text,
	"entry_date" text,
	"rank" text,
	"rank_grade" text,
	"awards" text,
	"conditions" text,
	"fly_fishing_level" text NOT NULL,
	"fly_tying_level" text NOT NULL,
	"rod_building_level" text NOT NULL,
	"fly_casting_level" text NOT NULL,
	"handedness" text,
	"retrieve_hand" text,
	"shirt_size" text,
	"shoe_size" text,
	"accessibility" text,
	"additional_info" text,
	"marital_status" text,
	"education" text,
	"employment" text,
	"personal_bio" text,
	"photo_url" text,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "programs" (
	"id" varchar(36) PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"description" text NOT NULL,
	"start_date" text NOT NULL,
	"end_date" text NOT NULL,
	"schedule" text NOT NULL,
	"capacity" integer NOT NULL,
	"registered_count" integer DEFAULT 0 NOT NULL,
	"image_url" text,
	"is_active" boolean DEFAULT true NOT NULL
);
--> statement-breakpoint
CREATE TABLE "registrations" (
	"id" varchar(36) PRIMARY KEY NOT NULL,
	"first_name" text NOT NULL,
	"last_name" text NOT NULL,
	"email" text NOT NULL,
	"phone" text NOT NULL,
	"participation_type" text DEFAULT 'participant' NOT NULL,
	"event_id" varchar(36),
	"program_id" varchar(36),
	"trip_id" varchar(36),
	"status" text DEFAULT 'pending' NOT NULL,
	"created_at" text NOT NULL,
	"notes" text,
	"is_archived" boolean DEFAULT false NOT NULL
);
--> statement-breakpoint
CREATE TABLE "trips" (
	"id" varchar(36) PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"description" text NOT NULL,
	"date" text NOT NULL,
	"end_date" text NOT NULL,
	"time" text NOT NULL,
	"end_time" text NOT NULL,
	"meetup_location" text NOT NULL,
	"destination" text NOT NULL,
	"capacity" integer NOT NULL,
	"registered_count" integer DEFAULT 0 NOT NULL,
	"duration_days" integer NOT NULL,
	"duration_nights" integer NOT NULL,
	"difficulty_level" text NOT NULL,
	"trip_coordinator_capacity" integer NOT NULL,
	"trip_coordinator_names" text,
	"volunteer_capacity" integer NOT NULL,
	"volunteer_names" text,
	"image_url" text,
	"is_active" boolean DEFAULT true NOT NULL
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" varchar(36) PRIMARY KEY NOT NULL,
	"username" text NOT NULL,
	"password" text NOT NULL,
	CONSTRAINT "users_username_unique" UNIQUE("username")
);
--> statement-breakpoint
CREATE TABLE "volunteer_registrations" (
	"id" varchar(36) PRIMARY KEY NOT NULL,
	"first_name" text NOT NULL,
	"middle_initial" text,
	"last_name" text NOT NULL,
	"street" text NOT NULL,
	"city" text NOT NULL,
	"state" text NOT NULL,
	"postal_code" text NOT NULL,
	"country" text NOT NULL,
	"email" text NOT NULL,
	"mobile_phone" text,
	"work_phone" text,
	"home_phone" text,
	"preferred_phone" text NOT NULL,
	"birth_year" integer NOT NULL,
	"is_teen" boolean,
	"gender" text NOT NULL,
	"ethnicity" text NOT NULL,
	"did_serve" boolean NOT NULL,
	"emergency_first_name" text NOT NULL,
	"emergency_last_name" text NOT NULL,
	"emergency_relationship" text NOT NULL,
	"emergency_email" text,
	"emergency_mobile_phone" text NOT NULL,
	"emergency_work_phone" text,
	"emergency_home_phone" text,
	"phwff_connection" text NOT NULL,
	"leadership_role" text NOT NULL,
	"region" text NOT NULL,
	"start_date" text NOT NULL,
	"va_volunteer" boolean NOT NULL,
	"allergies" text,
	"skills" text,
	"fly_fishing_level" text NOT NULL,
	"fly_tying_level" text NOT NULL,
	"rod_building_level" text NOT NULL,
	"fly_casting_level" text NOT NULL,
	"handedness" text,
	"retrieve_hand" text,
	"shirt_size" text,
	"shoe_size" text,
	"accessibility" text,
	"additional_info" text,
	"marital_status" text,
	"education" text,
	"employment" text,
	"personal_bio" text,
	"photo_url" text,
	"created_at" timestamp DEFAULT now() NOT NULL
);
