ALTER TABLE events ALTER COLUMN "date" DROP NOT NULL;
ALTER TABLE events ALTER COLUMN "time" DROP NOT NULL;
ALTER TABLE programs ALTER COLUMN start_date DROP NOT NULL;
ALTER TABLE programs ALTER COLUMN end_date DROP NOT NULL;
ALTER TABLE trips ALTER COLUMN "date" DROP NOT NULL;
ALTER TABLE trips ALTER COLUMN end_date DROP NOT NULL;
